### ISSUE TITLE
src/sage/all.py  # 1 doctest failed (`local/etc/sage-started.txt` does not exist.)

### ISSUE THREAD

**Issue by jakobkroeker** [sagemath/sage-patchbot#100]
`sage -t src/sage/all.py` regularly fails  on my computer for a virgin sage installation: 
`sage-starts` is never called and thus
`local/etc/sage-started.txt` does not exist.

After manually running `sage-starts`,
the test passes:
```
sage -t --long --warn-long 72.4 src/sage/all.py
    [20 tests, 1.54 s]
----------------------------------------------------------------------
All tests passed!
```

And once created, without a distclean `local/etc/sage-started.txt`  will never be removed..

**Comment by fchapoton** [comment]
I have added a call to sage-starts after every "make build".

**Comment by koffie** [comment]
Hi @fchapoton I just ran into this exact same issue, but I don't seem to be able to find the trac ticket for this.

**Comment by fchapoton** [comment]
Has this something to do with the patchbot ? I have fixed this in the patchbot long ago.

**Comment by koffie** [comment]
No I ran into this just with a plane sage installation, I guess make build is not the right commando to type if you want to build sage but not the documentation. make start should solve the problem.
