### ISSUE TITLE
Clean shutdown of patchbot

### ISSUE THREAD

**Issue by embray** [sagemath/sage-patchbot#113]
It would be nice to have a mechanism for cleanly shutting down a patchbot, albeit not immediately, such that it exits after finishing the current ticket it's working on.  For example, we could use `SIGUSR1` for this purpose--when received the patchbot would just set a flag to exit after finishing the current ticket it's working on.

The Docker patchbot, for example, gets rebuilt every now and then, and it would be nice to have a mechanism to launch a new patchbot from the new Docker image, while giving the current patchbot from the previous image a chance to finish what it's working on first, so that it's not wasted effort.  This would probably be useful outside the context of Docker images as well.

**Comment by fchapoton** [comment]
Merged. Thanks.

**Comment by embray** [comment]
Thanks!
