### ISSUE TITLE
default sort order should be inversed

### ISSUE THREAD

**Issue by saraedum** [sagemath/sage-patchbot#116]
When patchbot request the ticket list with `?raw&status=open` the tickets are sorted *ascending* by last activity and then the first 1000 are returned. This currently means that a few new tickets are excluded. We should invert the sorting.

**Comment by fchapoton** [comment]
Now tickets are sorted by descending "last_trac_activity". Beware that "last_activity" means last patchbot activity.

**Comment by saraedum** [comment]
This does not seem to work.
```
[2017-07-19 15:46:28] Getting ticket list...
[2017-07-19 15:46:47] no more tickets, take a nap
```

**Comment by saraedum** [comment]
Nevermind. My bad.
