### ISSUE TITLE
Release 2.8.0

### ISSUE THREAD

**Issue by embray** [sagemath/sage-patchbot#131]
@fchapoton The next release should have been tagged 2.8.0, not 2.8.1.  Also the changelog is intended to grow up , not down.  I haven't actually *documented* the release process but I was following my usual process for Python packages.  I'm going to delete the 2.8.1 tag you made and re-do the release as 2.8.0.

**Comment by fchapoton** [comment]
ok, as you like.. You know better what to do.

**Comment by embray** [comment]
Done.  The next release is versioned 2.8.1, but if we add new features in the meantime we can change it to 2.9.0 at release prep time (the user base and scale of the patchbot are such that it's probably not necessary to maintain separate bug fix releases :)
