### ISSUE TITLE
@overload decorator from the typing module triggers spurious coverage errors

### ISSUE THREAD

**Issue by egourgoulhon** [sagemath/sage-patchbot#161]
The coverage plugin seems to misinterpret the @overload syntax of the typing module (https://docs.python.org/3/library/typing.html), reporting some lack of coverage when it is used. See https://trac.sagemath.org/ticket/29775 for a example.

**Comment by fchapoton** [comment]
this is using `sage -coverage`, nothing to do with the patchbot

**Comment by egourgoulhon** [comment]
Ah yes, you are perfectly right!
