### ISSUE TITLE
Refactor into Python package

### ISSUE THREAD

**Issue by embray** [sagemath/sage-patchbot#79]
I found it jarring, when working on getting the patchbot Docker container working, then when installed in sage the patchbot lives in a *directory* under `local/bin`.  I expected it would be a python package installed into the appropriate site-packages, and that there would be a `patchbot` script that would import its functionality from that package.  This would include adding a `setup.py` script, etc., and fixing up the inter-module imports to use the full package name, rather than implicit relative imports.

I'm happy to do this work if there's no strong reason against this.

**Comment by fchapoton** [comment]
Well, this is well above my competences, but if you want to do that, I have just one objection:

You should note that the patchbot sources contains 2 different things. Namely, code for the patchbot server and code for the patchbot clients. They cannot be easily disentangled.
**Any change should not break the server.**

**Comment by embray** [comment]
That shouldn't be a problem--part of the point of developing a package is that the *library* part of the code can be used by different interfaces--in this case the server and client components which both share some of the same library code as far as I can tell.

**Comment by fchapoton** [comment]
Ok, then you can do that. I will probably then need help on the server side to keep it running in a new way, because I do not really understand how it works.

Maybe you should ask Robert Bradshaw to be added as a participant with full rights on the project ?

**Comment by embray** [comment]
Perhaps. I don't think it will significantly change anything about how it's run. It's just a slight code reorganization so that it's not using anti-patterns like implicit relative imports, and installing directories full of Python code into `bin/` :)  But I'll make sure it works and point out any changes in the documentation.

**Comment by fchapoton** [comment]
Would you be ready to help now ? I have made the preliminary work of changing imports, but I am stuck
with the package creation.

**Comment by embray** [comment]
I actually started on this a while back when I first made the ticket, but have been distracted by other things.  Let me see about rebasing my existing work on your changes.

**Comment by fchapoton** [comment]
There are many things not clear to me. Should I install the patchbot python package into sage python or
into the system python (current situation) ?

And also, by what should I replace (in the sage launch script sage/local.bin/sage)
```
if [ "$1" = '-patchbot' -o "$1" = "--patchbot" ]; then
    shift
    cd "$SAGE_ROOT"
    exec local/bin/patchbot/patchbot.py "$@"
fi
```

And also, I do not clearly understand if I must create scripts for the patchbot, what they must look like, and where to put them.

**Comment by embray** [comment]
@fchapoton Sorry, I missed this before.

I don't know why the patchbot would have been installed into the system python.  I assume it should be installed like anything else sage-related into Sage's root using its Python.  It does't really matter though--a properly constructed `setup.py` installs into the appropriate site-packages for the python it was run with--that's art of the point.

For the second question, it's nice that there's already a `main()` function in `sage_patchbot.patchbot`.  You can use use the `console_scripts` entry point to automatically generate and install a wrapper script for the main function--I would call it just `patchbot`:

```
setup(
    ...
    entry_points = {
        'console_scripts': ['patchbot=sage_patchbot.patchbot:main'],
    }
    ...
)
```

Then in the launcher script it would suffice to run `$SAGE_LOCAL/bin/patchbot`.  I don't know whether or not it's important for the patchbot to also cd to `$SAGE_ROOT`.

**Comment by fchapoton** [comment]
I tried to do the job at http://trac.sagemath.org/ticket/20736

but the install is failing so I must have done something wrong.

**Comment by embray** [comment]
how is the install failing?  Is there a build log somewhere I can look at?

**Comment by fchapoton** [comment]
[install] make[1] : on entre dans le répertoire « /home/chapoton/sage/build/make »
[install] sage-logger -p 'sage-spkg  patchbot-2.5.8' '/home/chapoton/sage/logs/pkgs/patchbot-2.5.8.log'
[install] [patchbot-2.5.8] Found local metadata for patchbot-2.5.8
[install] [patchbot-2.5.8] Using cached file /home/chapoton/sage/upstream/patchbot-2.5.8.tar.bz2
[install] [patchbot-2.5.8] patchbot-2.5.8
[install] [patchbot-2.5.8] ====================================================
[install] [patchbot-2.5.8] Setting up build directory for patchbot-2.5.8
[install] [patchbot-2.5.8] mv: cannot stat 'patchbot-2.5.8*': No such file or directory
[install] [patchbot-2.5.8] Finished set up
[install] [patchbot-2.5.8] ****************************************************
[install] [patchbot-2.5.8] Host system:
[install] [patchbot-2.5.8] Linux pc-chapoton 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[install] [patchbot-2.5.8] ****************************************************
[install] [patchbot-2.5.8] C compiler: gcc
[install] [patchbot-2.5.8] C compiler version:
[install] [patchbot-2.5.8] Using built-in specs.
[install] [patchbot-2.5.8] COLLECT_GCC=gcc
[install] [patchbot-2.5.8] COLLECT_LTO_WRAPPER=/home/chapoton/sage/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.3/lto-wrapper
[install] [patchbot-2.5.8] Target: x86_64-unknown-linux-gnu
[install] [patchbot-2.5.8] Configured with: ../src/configure --prefix=/home/chapoton/sage/local --with-local-prefix=/home/chapoton/sage/local --with-gmp=/home/chapoton/sage/local --with-mpfr=/home/chapoton/sage/local --with-mpc=/home/chapoton/sage/local --with-system-zlib --disable-multilib --disable-nls --enable-languages=c,c++,fortran --disable-libitm
[install] [patchbot-2.5.8] Thread model: posix
[install] [patchbot-2.5.8] gcc version 4.9.3 (GCC)
[install] [patchbot-2.5.8] ****************************************************
[install] [patchbot-2.5.8] python: can't open file 'setup.py': [Errno 2] No such file or directory
[install] [patchbot-2.5.8] Error installing sage_patchbot ... exiting
[install] [patchbot-2.5.8]
[install] [patchbot-2.5.8] real	0m0.009s
[install] [patchbot-2.5.8] user	0m0.004s
[install] [patchbot-2.5.8] sys	0m0.000s
[install] [patchbot-2.5.8] ************************************************************************
[install] [patchbot-2.5.8] Error installing package patchbot-2.5.8
[install] [patchbot-2.5.8] ************************************************************************
[install] [patchbot-2.5.8] Please email sage-devel (http://groups.google.com/group/sage-devel)
[install] [patchbot-2.5.8] explaining the problem and including the relevant part of the log file
[install] [patchbot-2.5.8] /home/chapoton/sage/logs/pkgs/patchbot-2.5.8.log
[install] [patchbot-2.5.8] Describe your computer, operating system, etc.
[install] [patchbot-2.5.8] If you want to try to fix the problem yourself, *don't* just cd to
[install] [patchbot-2.5.8] /home/chapoton/sage/local/var/tmp/sage/build/patchbot-2.5.8 and type 'make' or whatever is appropriate.
[install] [patchbot-2.5.8] Instead, the following commands setup all environment variables
[install] [patchbot-2.5.8] correctly and load a subshell for you to debug the error:
[install] [patchbot-2.5.8] (cd '/home/chapoton/sage/local/var/tmp/sage/build/patchbot-2.5.8' && '/home/chapoton/sage/sage' --sh)
[install] [patchbot-2.5.8] When you are done debugging, you can type "exit" to leave the subshell.
[install] [patchbot-2.5.8] ************************************************************************
[install] Makefile:2252 : la recette pour la cible « /home/chapoton/sage/local/var/lib/sage/installed/patchbot-2.5.8 » a échouée
[install] make[1]: *** [/home/chapoton/sage/local/var/lib/sage/installed/patchbot-2.5.8] Erreur 1
[install] make[1] : on quitte le répertoire « /home/chapoton/sage/build/make »
[install] 
[install] real	0m0.392s
[install] user	0m0.272s
[install] sys	0m0.048s
[install] ***************************************************************
[install] Error building Sage.
[install] 
[install] The following package(s) may have failed to build (not necessarily
[install] during this run of 'make patchbot'):
[install] 
[install] * package: patchbot-2.5.8
[install] log file: /home/chapoton/sage/logs/pkgs/patchbot-2.5.8.log
[install] build directory: /home/chapoton/sage/local/var/tmp/sage/build/patchbot-2.5.8
[install] 
[install] The build directory may contain configuration files and other potentially
[install] helpful information. WARNING: if you now run 'make' again, the build
[install] directory will, by default, be deleted. Set the environment variable
[install] SAGE_KEEP_BUILT_SPKGS to 'yes' to prevent this.
[install] 
Makefile:16 : la recette pour la cible « patchbot » a échouée
make: *** [patchbot] Erreur 1

**Comment by fchapoton** [comment]
Could this be a problem of name conflict between "patchbot" (name of the pkg in sage)
and sage-patchbot (name of the python package) ?

**Comment by jdemeyer** [comment]
> I expected it would be a python package installed into the appropriate site-packages

`site-packages` is most likely **not** appropriate in this case, since the patchbot should be run using the system Python.

**Comment by fchapoton** [comment]
Why should it be run using the system python ? It is currently doing so, but why should we keep that behaviour ?

**Comment by embray** [comment]
> site-packages is most likely not appropriate in this case, since the patchbot should be run using the system Python.

Well, that *is* likely appropriate in this case where "site-packages" refers to `/<system_prefix>/lib/pythonX.Y/site-packages`

**Comment by jdemeyer** [comment]
On the other hand, why not keep the patchbot as an external script and not a Python package.

What is wrong with the status-quo?

**Comment by fchapoton** [comment]
As explained before, one major issue is that currently the patchbot installs its source directory right in
the middle of $SAGE_ROOT/local/bin, which is not a very nice thing to do.

**Comment by embray** [comment]
> What is wrong with the status-quo?

Any Python code consisting of multiple modules should be grouped into a package, not a bunch of loose modules added to sys.path in an ad-hoc manner, much less dumped into `bin/`.

**Comment by fchapoton** [comment]
This is mostly done, but need now to be used and double-checked. See trac ticket #20736

**Comment by fchapoton** [comment]
The patchbot is now a python package. Old sage package for patchbot is obsolete.
