### ISSUE TITLE
Move this repository to sagemath organization on GitHub

### ISSUE THREAD

**Issue by embray** [sagemath/sage-patchbot#82]
With all due respect to @robertwb and his tireless work on this of course :)  But every time I go to try to find this repository I momentarily forget that it's not under sagemath/ despite sage being its primary (only?) user.

**Comment by fchapoton** [comment]
yes. How to do that ? Can this be done by Robert only ?

**Comment by embray** [comment]
Possibly. I don't know what level of permissions you have on this repo.  If you do have admin permissions you can go to the settings for the repository, and toward the bottom in the "Danger Zone" there is an option to transfer repository ownership.

**Comment by fchapoton** [comment]
I do not have a setting menu.

@robertwb, could you please do the transfer of ownership ?

**Comment by fchapoton** [comment]
done
