### ISSUE TITLE
autodetect number of cores. Do not use more threads than physically available cores 

### ISSUE THREAD

**Issue by jakobkroeker** [sagemath/sage-patchbot#94]
Do not use more threads than physically available cores,
otherwise sage tests will time out, leading to false negative result.

Proposal: 
autodetect number of cores.  set number of used cores to 
`max(parallelism, physically available #cores)`

Background: my machine has only 2 cores, but with the default parallelism=3 tests time out.

**Comment by fchapoton** [comment]
done in the latest commit : by default the parallelism is both smaller than 3 and than the number of cores.
